/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_realm_internal_Property */

#ifndef _Included_io_realm_internal_Property
#define _Included_io_realm_internal_Property
#ifdef __cplusplus
extern "C" {
#endif
#undef io_realm_internal_Property_PROPERTY_TYPE_INT
#define io_realm_internal_Property_PROPERTY_TYPE_INT 0L
#undef io_realm_internal_Property_PROPERTY_TYPE_BOOL
#define io_realm_internal_Property_PROPERTY_TYPE_BOOL 1L
#undef io_realm_internal_Property_PROPERTY_TYPE_FLOAT
#define io_realm_internal_Property_PROPERTY_TYPE_FLOAT 9L
#undef io_realm_internal_Property_PROPERTY_TYPE_DOUBLE
#define io_realm_internal_Property_PROPERTY_TYPE_DOUBLE 10L
#undef io_realm_internal_Property_PROPERTY_TYPE_STRING
#define io_realm_internal_Property_PROPERTY_TYPE_STRING 2L
#undef io_realm_internal_Property_PROPERTY_TYPE_DATA
#define io_realm_internal_Property_PROPERTY_TYPE_DATA 4L
#undef io_realm_internal_Property_PROPERTY_TYPE_ANY
#define io_realm_internal_Property_PROPERTY_TYPE_ANY 6L
#undef io_realm_internal_Property_PROPERTY_TYPE_DATE
#define io_realm_internal_Property_PROPERTY_TYPE_DATE 8L
#undef io_realm_internal_Property_PROPERTY_TYPE_OBJECT
#define io_realm_internal_Property_PROPERTY_TYPE_OBJECT 12L
#undef io_realm_internal_Property_PROPERTY_TYPE_ARRAY
#define io_realm_internal_Property_PROPERTY_TYPE_ARRAY 13L
/*
 * Class:     io_realm_internal_Property
 * Method:    nativeCreate
 * Signature: (Ljava/lang/String;ILjava/lang/String;ZZZ)J
 */
JNIEXPORT jlong JNICALL Java_io_realm_internal_Property_nativeCreate
  (JNIEnv *, jclass, jstring, jint, jstring, jboolean, jboolean, jboolean);

/*
 * Class:     io_realm_internal_Property
 * Method:    nativeClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_realm_internal_Property_nativeClose
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_Property
 * Method:    nativeGetName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_realm_internal_Property_nativeGetName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_Property
 * Method:    nativeGetType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_io_realm_internal_Property_nativeGetType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_Property
 * Method:    nativeGetObjectType
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_realm_internal_Property_nativeGetObjectType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_Property
 * Method:    nativeIsPrimary
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_Property_nativeIsPrimary
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_Property
 * Method:    nativeIsIndexed
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_Property_nativeIsIndexed
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_realm_internal_Property
 * Method:    nativeIsNullable
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_io_realm_internal_Property_nativeIsNullable
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
